### ISSUE TITLE
v1.0 TODO

### ISSUE THREAD

**Issue by pmrowla** [pmrowla/pylivemaker#41]
list of things needed to be done before v1.0 release

* [x] Deprecate Python 3.5
* [x] Core text blocks/lines API (#33, #37)
* [x] Core menus API (#19, #38)
* [x] CSV tools standardization (#42)
* [x] Label lookup
* [ ] Unify CSV tools into one command

**Comment by pmrowla** [comment]
1.0.0 has been deployed to pypi as-is. I've been busy with regular job things lately and haven't had time to get to the rest, so everything else will need to be pushed into 1.1
